version: '3.9'

services:
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=development  # Define el entorno como desarrollo
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres  # Conexión a PostgreSQL
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres